import Head from "next/head";
import { Hero } from "@/pages-component/landing";

import cls from "../styles/home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={cls.container}>
        <Hero />
      </div>
    </>
  );
}
